#pragma once

#include <phonemis/base/phonemizer/lexicon_phonemizer.h>

#include <string>
#include <string_view>
#include <unordered_set>

namespace phonemis::zh {

/**
 * Reads Mandarin words from a lexicon of single characters and phrases, generated by
 * scripts/tools/create_zh_lexicon.py. A word is split into phrases the way pypinyin
 * splits it: the longest phrase from the left, with a character read on its own where
 * no phrase starts.
 */
class LexiconPhonemizer : public phonemizer::LexiconPhonemizer {
public:
  using Base = phonemizer::LexiconPhonemizer;
  using Base::phonemize;

  explicit LexiconPhonemizer(const phonemizer::Config& config);

  /**
   * Phonemizes one word of Han characters.
   * Characters missing from the lexicon are skipped.
   */
  std::u32string phonemize_word(std::u32string_view word) const;

private:
  // Every prefix of every phrase (multi-character entry), in UTF-8.
  std::unordered_set<std::string> phrase_prefixes_;
};

} // namespace phonemis::zh
