#pragma once

#include <phonemis/base/tagger/config.h>

#include <array>
#include <cstdint>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace phonemis::zh {

/**
 * Splits Mandarin text into words exactly as jieba.lcut() does by default: the most
 * probable path through a dictionary of word frequencies, with an HMM joining runs of
 * single characters into the words the dictionary does not know.
 * Its data file is generated by scripts/tools/create_zh_segmenter.py.
 */
class Segmenter {
public:
  explicit Segmenter(const tagger::Config& config);

  /**
   * Splits a run of Han characters into words.
   * @param text Han characters only (U+4E00..U+9FFF).
   * @returns the words, as views into `text`.
   */
  std::vector<std::u32string_view> segment(std::u32string_view text) const;

private:
  // A range [first, last) of dictionary words, sorted by code points.
  struct Range {
    size_t first;
    size_t last;
  };

  std::u32string_view word(size_t id) const;

  // Narrows `range`, whose words all start with the same `length` characters, to those
  // whose next character is `c`.
  Range extend(Range range, size_t length, char32_t c) const;

  // Frequency of a dictionary word, or 0 if `text` is not one.
  uint32_t frequency(std::u32string_view text) const;

  // Segments characters jieba covers (up to U+9FD5).
  void segment_known(std::u32string_view text, std::vector<std::u32string_view>& words) const;

  // Splits a run of characters the dictionary left single with the HMM.
  void segment_unknown(std::u32string_view text, std::vector<std::u32string_view>& words) const;

  // Dictionary, flattened: word i is words_[offsets_[i], offsets_[i + 1]).
  std::u32string words_;
  std::vector<uint32_t> offsets_;
  std::vector<uint32_t> frequencies_;
  double log_total_;

  // HMM over the states B(egin), E(nd), M(iddle) and S(ingle), indexed in this order,
  // which is also the order jieba breaks ties in. Values are log probabilities.
  std::array<double, 4> start_;
  std::array<std::array<double, 4>, 4> transitions_;
  std::array<std::unordered_map<char32_t, double>, 4> emissions_;
};

} // namespace phonemis::zh
