#!/usr/bin/env python3
import argparse
import sys

def generate_header(max_val: int):
    # Header boilerplate
    lines = [
        "#pragma once",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace phonemis::utils::unicode {",
        "",
        f"// Cover range 0x000 to 0x{max_val - 1:03X} ({max_val} characters)",
        f"constexpr size_t kLutSize = 0x{max_val:03X};",
        "",
        "struct UnicodeData {",
        "    char32_t lower;",
        "    char32_t upper;",
        "    bool is_alpha;",
        "};",
        "",
        "// This table is generated by a script or written out as a flat array",
        "inline constexpr std::array<UnicodeData, kLutSize> kUnicodeLut = {{"
    ]

    # Generate table entries
    for i in range(max_val):
        try:
            char = chr(i)
            # Some characters uppercase to multiple characters (e.g. 'ß' -> 'SS')
            # C++ case folding usually drops this or maps to a single character.
            # We'll just fall back to the original codepoint if length > 1.
            lower_str = char.lower()
            lower_cp = ord(lower_str) if len(lower_str) == 1 else i
            
            upper_str = char.upper()
            upper_cp = ord(upper_str) if len(upper_str) == 1 else i
            
            is_alpha = "true" if char.isalpha() else "false"
            
            # Simple printable representation for the comment
            if char.isprintable() and not char.isspace():
                comment = f"// '{char}'"
            else:
                comment = f"// 0x{i:04X}"
                
            entry = f"    {{0x{lower_cp:04X}, 0x{upper_cp:04X}, {is_alpha}}}, {comment}"
            lines.append(entry)
            
        except ValueError:
            # Handles edge cases (like surrogates if max > 0xD800)
            lines.append(f"    {{0x{i:04X}, 0x{i:04X}, false}}, // 0x{i:04X} (invalid)")

    # Footer boilerplate
    lines.extend([
        "}};",
        "",
        "} // namespace phonemis::utils::unicode"
    ])

    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(description="Generate a Unicode Look-Up Table (LUT) in C++.")
    # Allow input in base 10 (e.g., 1280) or base 16 (e.g., 0x500)
    parser.add_argument('--max', type=lambda x: int(x, 0), required=True,
                        help="Maximum number covered by the array (the size of the array)")
    parser.add_argument('--output', type=str, required=False,
                        help="Path to the output header file. If not provided, output to stdout.")
    
    args = parser.parse_args()

    cpp_code = generate_header(args.max)

    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(cpp_code)
        print(f"Generated header file successfully: {args.output}")
    else:
        print(cpp_code)

if __name__ == "__main__":
    main()